### ISSUE TITLE
Tentang Ridon

### ISSUE THREAD

**Issue by princeofgiri** [ridon/ridon.github.io#8]
Ridon adalah sistem operasi perangkat bergerak yang dibangun berdasarkan LineageOS dan Android Open Source Project.
Ridon bertujuan untuk meningkatkan kemampuan sumber daya manusia Indonesia agar memiliki kompetensi untuk bersaing di ranah teknologi perangkat bergerak.
Ridon saat ini masih dalam fase pengembangan sehingga banyak membutuhkan kontribusi dari teman-teman yang lain, terutama untuk pengujian dan pelaporan kutu.

**Comment by sendz** [comment]
@princeofgiri tambahin gambar lain?

**Comment by princeofgiri** [comment]
gambar sudah dikirm sama moko kan?

**Comment by sendz** [comment]
@sdmoko @princeofgiri nanti gambarnya diganti cuplikan layar aja.
