### ISSUE TITLE
Tambahin 1 halaman khusus untuk Legal

### ISSUE THREAD

**Issue by emhaye** [ridon/ridon.github.io#9]
Rujukan isinya https://www.lineageos.org/legal/

**Comment by raniaamina** [comment]
Sedang proses penerjemahan.

**Comment by raniaamina** [comment]
Mohon diperiksa.
cc: @sendz 
[Legal RIdon.zip](https://github.com/ridon/ridon.github.io/files/1346312/Legal.RIdon.zip)

**Comment by raniaamina** [comment]
# KETENTUAN LAYANAN

## SANGKALAN
Seluruh informasi dan berkas—baik dalam bentuk kode sumber atau berkas yang dapat dieksekusi—telah tersedia secara umum. Tidak ada garansi atau jaminan secara implisit yang diberikan. Seluruh risiko kerusakan yang mungkin terjadi ditanggung sepenuhnya oleh pengguna, termasuk kehilangan data, kerusakan peranti keras, atau kehilangan keuntungan dalam berbisnis. Silakan gunakan dengan risiko Anda tanggung sendiri. Perlu diperhatikan, jika perangkat Anda memiliki garansi, tindakan ini dapat membuat seluruh garansi yang menyertai perangkat Anda gugur karena Anda mengubah peranti lunak atau peranti keras yang terdapat pada sistem.

## KETENTUAN PENGGUNAAN
Beberapa citra, logo, gambar, dan karya lain yang berasal dari organisasi lain selain Ridon merupakan merek dagang dan/atau jasa yang tunduk pada undang-undang negara tempat mereka terdaftar. Penggunaan wajar materi dalam Ridon yang dilindungi hak cipta diatur dalam Undang-Undang Republik Indonesia Nomor 28 Tahun 2014 Tentang Hak Cipta. Jika Anda ingin menggunakan materi berhak cipta untuk tujuan personal yang melampaui penggunaan wajar, Anda harus mendapatkan izin dari pemegang hak cipta. Permintaan penghapusan hak cipta dapat dikirim ke posel humas@ridon.id.

## KEBIJAKAN PRIVASI
Privasi Anda merupakan hal yang utama bagi Ridon. Kebijakan privasi kami menjelaskan bagaimana kami mengumpulkan, menggunakan, mengungkapkan, mentransfer, dan menyimpan informasi Anda. Mohon luangkan waktu Anda untuk membiasakan diri dengan praktik privasi kami.

Ridon menyediakan sebuah sistem operasi dan aplikasi alternatif untuk berbagai gawai.

## INFORMASI YANG KAMI MILIKI
Informasi tertentu (seperti ID unik perangkat, model perangkat, dll) dikirimkan kepada kami semata-mata untuk mengukur dan mengidentifikasi metrik pemasangan personal. Informasi-informasi berikut tidak digunakan selain untuk tujuan yang tertera di bawah ini.
1. Informasi yang kami simpan dalam perangkat
    * ID unik perangkat (ID ini berubah saat perangkat disetel ulang ke pengaturan pabrik).
    * Model perangkat.
    * Berbagai versi peranti lunak kami yang dipasang dalam perangkat.
    * Negara asal perangkat terdaftar.
    * Operator nirkabel pada perangkat aktif yang terdaftar.
2. Informasi yang kami simpan dari partisipan ke platform ulasan kode kami
    * Alamat posel untuk mendaftar dan menfasilitasi ulasan.
    * Perjanjian Lisensi Kontribusi yang Ditandatangani (PLKD)
    * Alamat IP, aktivitas SSH, dan akses API yang mungkin tercatat untuk membatasi akses tertentu atau mencegah penyalahgunaan.
3. Informasi yang kami simpan untuk layanan sepintas
    * Alamat posel untuk mendaftar ke wiki dan melacak kutu pada peranti lunak.
Alamat IP yang mungkin tercatat untuk membatasi akses atau mencegah penyalahgunaan.
4. Informasi tambahan yang mungkin Anda berikan kepada kami
    * Laporan kutu yang disampaikan untuk memberikan dukungan mungkin berisi Informasi Pribadi (IP). Meskipun demikian, kami akan melakukan yang terbaik untuk mencegah pengumpulan informasi ini dari proses yang ada dalam kendali kami, penggunaan dan penyimpanan ini mungkin berisi IP sehingga Anda perlu untuk mengambil langkah guna membersihkan dan memvalidasi data terkait sebelum diajukan.

## OPT-OUT
Anda dapat memilih keluar dari statistik perangkat Ridon melalui opsi Privasi yang terdapat dalam menu Pengaturan di perangkat Anda.

## LAMAN
Seperti yang terjadi pada sebagian situs/laman web, kami mengumpulkan beberapa informasi secara otomatis dan menyimpannya dalam berkas log. Informasi ini mencakup alamat Protokol Internet (IP), tipe peramban (termasuk versi) dan bahasa, penyedia layanan internet, halaman referensi, sistem operasi, waktu akses, dan aktivitas Anda selama mengakses situs.
Kami dapat mengumpulkan informasi mengenai aktivitas pengguna di situs, produk, dan layanan kami yang lain. Informasi ini dikumpulkan dan digunakan untuk membantu kami memberikan informasi yang lebih bermanfaat kepada pengguna dalam memahami bagian mana dari situs/laman web, produk, dan layanan kami yang paling diminati serta untuk memeriksa sistem secara umum. Data gabungan dianggap sebagai informasi nonpribadi untuk tujuan Kebijakan Privasi ini.
Kami tidak mengumpulkan informasi pribadi dari anak-anak di bawah 13 tahun secara sengaja, kecuali jika orang tua telah membuatkan akun untuk anak mereka dan memberikan Ridon akses secara khusus. Jika kami mendeteksi bahwa sistem telah mengumpulkan informasi pribadi anak di bawah usia 13 tahun tanpa terlebih dahulu menerima izin orang tua yang dapat diverifikasi, kami akan mengambil langkah-langkah untuk menghapus informasi tersebut sesegera mungkin.

## INFORMASI YANG MUNGKIN DIBAGIKAN
Kami tidak membagikan informasi Anda dengan perusahaan, organisasi, atau individu di luar Ridon, kecuali jika salah satu dari keadaan berikut berlaku.
 - Mendapat persetujuan dari Anda (penyampaian laporan kutu termasuk dalam bagian ini),
 - bila diperlukan secara hukum.

Kami akan membagikan informasi yang kami miliki dengan entitas di luar Ridon jika kami memiliki keyakinan bahwa akses, penggunaan, penjagaan, atau pengungkapan informasi tersebut diperlukan untuk:
 - memenuhi hukum, peraturan, dan proses hukum yang berlaku serta permintaan pemerintah yang dapat dilaksanakan,
 - memberlakukan Persyaratan Layanan yang berlaku, termasuk menyelidiki kemungkinan pelanggaran,
 - mendeteksi, mencegah, atau mengatasi masalah kecurangan, keamanan, atau teknis,
 - melindungi hak, kepemilikan, dan keamanan Ridon serta pengguna kami dan masyarakat umum dari pelanggaran sebagaimana yang dipersyaratkan atau diizinkan oleh undang-undang.

Kami akan memperbarui kebijakan privasi ini seperlunya agar lebih akurat dan lebih jelas.

**Comment by princeofgiri** [comment]
+1

**Comment by emhaye** [comment]
:+1:

**Comment by sendz** [comment]
saya generate ke html pake ini https://dillinger.io/
